# Generated by Django 3.0.4 on 2020-03-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('aadharno', models.CharField(max_length=12)),
                ('panno', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
